apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: janusgraph-demo-project4
spec:
  type: LoadBalancer
  ports:
    - port: 8182
      targetPort: 8182
  selector:
    app: example
